# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clean
      run: xcodebuild clean
    - name: Run tests
      run: xcodebuild archive -scheme Kimis -archivePath ./build/Kimis.xcarchive -sdk iphoneos -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED=NO
    - name: Pack
      run: xcrun -sdk iphoneos PackageApplication -v ./build/Kimis.xcarchive/Products/Applications/Kimis.app -o ./build/Kimis.ipa

    - uses: actions/upload-artifact@v4.4.3
      with:
        name: Kimis
        path: ./build
